(function(){
var h=!0,k=!1,n=window,p=document;function q(){}var r=function(){this.prefix="gtm.";this.g={}};r.prototype.set=function(a,b){this.g[this.prefix+a]=b};r.prototype.get=function(a){return this.g[this.prefix+a]};function aa(a){return"function"==typeof a}function s(a){return"[object Array]"==Object.prototype.toString.call(Object(a))}function t(a,b){if(Array.prototype.indexOf)return a.indexOf(b);for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1}
function ba(a){return a?a.replace(/^\s+|\s+$/g,""):""}function ca(){return new Image(1,1)}function da(){return new Date}function ea(a){var b=p.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function u(a,b,c){return("http:"==n.location.protocol?b:a)+c}
function v(a,b){var c=p.createElement("script");c.type="text/javascript";c.async=h;c.src=a;b&&(c.onload=c.onreadystatechange=function(){if(!c.readyState||"loaded"==c.readyState||"complete"==c.readyState)c.onload=q,c.onreadystatechange=q,b()});ea(c)}function fa(a){var b=p.createElement("iframe");b.height="0";b.width="0";b.style.display="none";b.style.visibility="hidden";ea(b);b.src=a}function y(a){var b=ca();b.onload=function(){b.onload=null};b.src=a}
function ga(a,b,c,d){var e="addEventListener",f="attachEvent";if(a[e])a[e](b,c,!!d);else if(a[f])a[f]("on"+b,c)}function Ma(){return C}

function E(){var a=D.get("gtm.url");a||(a=n.location,a=a.hash?a.href.replace(a.hash,""):a.href);return a}
function Ua(a){return String(a[""])==String(a[""])}
var _e=Ma;_e.b="e";var _eq=Ua;_eq.b="eq";
var _u=E;_u.b="u";var I=function(){this.c=[]};I.prototype.set=function(a,b){this.c.push([a,b]);return this};I.prototype.d=function(){for(var a={},b=0;b<this.c.length;b++)a[J(this.c[b][0])]=J(this.c[b][1]);return a};
function K(a){this.index=a;this.d=function(){return L(M[a])}}function _M(a){return new K(a)}function N(a){this.d=function(){for(var b=[],c=0;c<a.length;c++)b.push(J(O[a[c]]));return b.join("")}}function _T(a){return new N(arguments)}
function P(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return h;return k}this.d=function(){if(a[0]instanceof K&&b(8)&&b(16))return'google_tag_manager["GTM-S9LQ"].macro('+a[0].index+")";for(var c=String(J(a[0])),d=1;d<a.length;d++)c=z[a[d]](c);return c}}function _E(a,b){return new P(arguments)}
function J(a){var b=a;if(a instanceof K||a instanceof I||a instanceof N||a instanceof P)return a.d();if(s(a))for(var b=[],c=0;c<a.length;c++)b[c]=J(a[c]);else if(a&&"object"==typeof a)for(c in b={},a)a.hasOwnProperty(c)&&(b[c]=J(a[c]));return b}var Q=0,O=sb([]),tb=R(0,""),M=R(1,""),S=R(1,""),T=R(1,""),ub=R(2,"");function sb(a){for(var b=[],c=0;c<a.length;c++)b[c]=W(c,a);return b}function W(a,b){var c=b[a],d=c;if(c instanceof K||c instanceof P||c instanceof N)d=c;else if(s(c))for(var d=[],e=0;e<c.length;e++)d[e]=W(c[e],b);else if("object"==typeof c)for(e in d=new I,c)c.hasOwnProperty(e)&&d.set(b[e],W(c[e],b));return d}
function R(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=O[e[1]]);if(1==a)for(var f=X(e[0]),e=c[d]={},g=0;g<Q;g++)f[g]&&(e[tb[g][0]]=tb[g][1]);if(2==a)for(g=0;4>g;g++)e[g]=X(e[g]);}return c}
function X(a){for(var b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",c=[],d=0;d<Q;d++){var e=a&&a.charAt(Math.floor(d/6))||"A";c[d]=1<<d%6&b.indexOf(e)?1:0}return c}var C,Y={set:function(a,b){D.set(a,b)},event:function(a){C=a;var b=zb();C=null},macro:function(a){return M[a]&&L(J(M[a]))}};var Z={push:function(a){for(var b=arguments,c=0;c<b.length;c++)try{if(aa(b[c][0]))b[c][0]();else Y[b[c][0]].apply(Y,[].slice.call(b[c],1))}catch(d){}}};function Ab(){var a=n["gtm"];if(a){var b=a.a;s(b)&&Z.push.apply(Z,b);a.a=Z}}function Bb(){var a=n.google_tag_manager;a||(a=n.google_tag_manager={});a["GTM-S9LQ"]||(a["GTM-S9LQ"]=Y)}var $=[];
function Cb(a){for(var b in a)a.hasOwnProperty(b)&&Y.set(b,a[b]);if(a["gtm.start"]&&(b=Math.random(),0.01>b)){var c=(new Date).getTime()-a["gtm.start"];y("//www.googletagmanager.com/a?v=1&id=GTM-S9LQ&cv=&l="+c+"&cb="+b)}a.event&&Y.event(a.event)}function Db(){for(;null==C&&0<$.length;)Cb($.shift())}function Eb(){var a=n["dataLayer"];if(a){var b=a.push;a.push=function(){var c=[].slice.call(arguments,0);b.apply(a,c);$.push.apply($,c);Db()};$.push.apply($,a.slice(0));Db()}}var D=new r;
function L(a){return a[""](a)}function Fb(a){return function(b){if(void 0===a[b]){var c=S[b]&&J(S[b]);a[b]=[c&&L(c),c]}return a[b]}}function Gb(a,b){for(var c=0;c<Q;c++)if(a[0][c]&&!b(c)[0]||a[2][c]&&b(c)[0])return k;return h}function Hb(a,b,c){for(var d=0;d<Q;d++)b[d]=b[d]||a[1][d],c[d]=c[d]||a[3][d]}function Ib(a,b){for(var c=D.get("tagTypeBlacklist")||[],d=[],e=0;e<Q;e++)a[e]&&(!b[e]&&0>t(c,T[e][""].b))&&(d[e]=J(T[e]));return d}
function Jb(a,b,c){for(var d=D.get("tagTypeBlacklist")||[],e=0;e<Q;e++)if(a[e]&&!b[e]&&0>t(d,T[e][""].b)){L(c[e])}}
function zb(){var a=[];for(var d=X(),e=X(),f=Fb([]),c=0;c<ub.length;c++){var g=ub[c],w=Gb(g,f);w&&Hb(g,d,e);}f=Ib(d,e);Jb(d,e,f);return a}Bb();Ab();Eb();
var Kb=k;function Lb(){if(!Kb){Kb=h;var a=n["dataLayer"];a?a.push({event:"gtm.dom"}):Y.event("gtm.dom")}}function Mb(){"complete"===p.readyState?Lb():ga(n,"load",Lb)}Mb();var _vs="res_ts:1349353549864000,tpl_cl:38808444,srv_cl:38545329,ds:live,cv:";
})()
